name = "godia-prime-solutions"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "godia-prime-connect-db"
database_id = "c549b601-25e8-48f1-a2a5-e83127cc2302"
